collector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url('^', include('django.contrib.auth.urls')),
    url(r'^track/', include('track.urls')),
    url(r'^admin/', admin.site.urls),
]

track/urls.py
from django.conf.urls import url

from . import views, auths

app_name = 'track'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^login/$', auths.auth_login, name='auth-login'),
    url(r'^logout/$', auths.auth_logout, name='auth-logout'),
    url(r'^register/$', auths.auth_register, name='auth-register'),

    url(r'^upload-edit/(?P<upload_id>[0-9]*)$', views.upload_edit, name='upload-edit'),
    url(r'^upload-delete/(?P<upload_id>[0-9]+)$', views.upload_delete, name='upload-delete'),
    url(r'^upload/(?P<upload_id>[0-9]+)$', views.upload_view, name='upload-view'),
    url(r'^upload-raw/(?P<upload_id>[0-9]+)$', views.upload_raw, name='upload-raw'),

    url(r'^title-list/$', views.title_list, name='title-list'),
    url(r'^title-edit/(?P<title_id>[0-9]*)$', views.title_edit, name='title-edit'),
    url(r'^title-delete/(?P<title_id>[0-9]+)$', views.title_delete, name='title-delete'),
    url(r'^title/(?P<title_id>[0-9]+)$', views.title_view, name='title-view'),

    url(r'^title/(?P<title_id>[0-9]+)/release-edit/(?P<release_id>[0-9]*)$', views.release_edit, name='release-edit'),
    url(r'^title/(?P<title_id>[0-9]+)/release-delete/(?P<release_id>[0-9]+)$', views.release_delete, name='release-delete'),
    url(r'^title/(?P<title_id>[0-9]+)/release-upload/(?P<release_id>[0-9]+)$', views.release_upload, name='release-upload'),

    url(r'^release-get-options/$', views.release_get_options, name='release-get-options'),
]

track/models.py
import re
from django.db import models
from datetime import datetime
from django.contrib.auth.models import User as AuthUser

# Create your models here.
class Title(models.Model):
  title_text = models.CharField(max_length=200)
  summary_text = models.CharField(max_length=2000)
  year_start = models.IntegerField()
  year_end = models.IntegerField(blank=True, null=True)
  episodes = models.IntegerField()
  runtime_minutes = models.IntegerField()
  cover_url = models.CharField(max_length=200)
  status = models.SmallIntegerField(default=0)
  #
  def __str__(self):
    return self.title_text;
  #
  def get_release_list(self):
    return self.release_set.all().order_by('-pub_date')
  #
  def can_modify(self, request):
    return request.user.is_staff or self.status == 0

class User(models.Model):
  avatar_url = models.CharField(max_length=200)
  auth = models.ForeignKey(AuthUser, on_delete=models.PROTECT)

class Release(models.Model):
  title = models.ForeignKey(Title, on_delete=models.PROTECT)
  release_text = models.CharField(max_length=200)
  user = models.ForeignKey(AuthUser, on_delete=models.PROTECT)
  video_text = models.CharField(max_length=200)
  audio_text = models.CharField(max_length=200)
  subs_text = models.CharField(max_length=200)
  pub_date = models.DateTimeField('date published')
  #
  def __str__(self):
    return self.release_text;
  #
  def get_upload_list(self):
    return self.upload_set.all().order_by('-pub_date')
  #
  def can_modify(self, request):
    return request.user.is_staff or self.user.id == request.user.id

class Upload(models.Model):
  release = models.ForeignKey(Release, on_delete=models.CASCADE)
  user = models.ForeignKey(AuthUser, on_delete=models.PROTECT)
  upload_text = models.CharField(max_length=200)
  host_list = models.CharField(max_length=200, default='')
  link_crc32 = models.BigIntegerField(default=0)
  pub_date = models.DateTimeField(default=datetime.now)
  #
  def __str__(self):
    return self.upload_text;
  #
  def get_host_list(self):
    values = self.link_set.order_by('host').distinct().values_list('host', flat=True)
    return ', '.join(values);
  #
  def get_upload_host_ordered(self):
    return self.upload_host_set.order_by('host')
  #
  def can_modify(self, request):
    return request.user.is_staff or self.user.id == request.user.id

class Host(models.Model):
  hostname = models.CharField(max_length=100, primary_key=True)
  image = models.CharField(max_length=100, default='default.png')
  #
  def __str__(self):
    return self.hostname;

class Upload_Host(models.Model):
  upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
  host = models.ForeignKey(Host, on_delete=models.PROTECT)

class Link(models.Model):
  upload = models.ForeignKey(Upload, on_delete=models.CASCADE)
  link_url = models.CharField(max_length=2000)
  link_text = models.CharField(max_length=200)
  host = models.ForeignKey(Host, on_delete=models.PROTECT)
  #
  def __str__(self):
    return self.link_text;
  #
  def get_host(self):
    if self.link_url[:7] == 'magnet:':
      return 'torrent'
    elif self.link_url[:5] == 'ed2k:':
      return 'ed2k'
    elif self.link_url[-8:] == '.torrent':
      return 'torrent'
    else:
      match = re.findall(r'(?:^[a-z0-9]+\:\/\/)([^\/]+)', self.link_url.lower())
      if len(match) > 0: return match[0]
      else: return self.link_url

  #
  def get_link_line(self):
    if self.link_text == self.link_url:
      return self.link_url
    return self.link_url +"<"+ self.link_text

track/views.py
import re
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_list_or_404, get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.core.exceptions import SuspiciousOperation
from .models import Upload, Title, Release, Link, Host, Upload_Host

# Create your views here.
def index(request):
  upload_list = Upload.objects.all().order_by('-pub_date')
  return render(request, 'track/index.html', {'upload_list': upload_list})

#
# Unauthorized
#
def unauthorized():
  return HttpResponseRedirect(reverse('track:index', args=()))

#
# Upload
#
def upload_view(request, upload_id):
  upload = get_object_or_404(Upload, pk=upload_id)
  return render(request, 'track/upload-view.html', {'upload': upload})

@login_required
def upload_edit_error(request, upload_id, error):
  titles_list = Title.objects.all().order_by('title_text')

  upload = None
  if upload_id != '0':
    upload = get_object_or_404(Upload, pk=upload_id)
    if not upload.can_modify(request):
      return unauthorized()

  return render(request, 'track/upload-edit.html', {'titles_list': titles_list,
                                                    'upload': upload,
                                                    'error_message': error})

@login_required
def upload_edit(request, upload_id):
  if not request.POST:
    return upload_edit_error(request, upload_id, '')

  if request.POST.get('title_id') == '0':
    return upload_edit_error(request, upload_id, "No hi ha cap anime seleccionat")

  if request.POST.get('release_id') == '':
    return upload_edit_error(request, upload_id, "No hi ha cap release seleccionada")

  links_str = request.POST.get('links').strip()
  if links_str == "":
    return upload_edit_error(request, upload_id, "Falta la llista d'enllaços")

  if upload_id != '0':
    u = get_object_or_404(Upload, pk=upload_id)
    if not u.can_modify(request):
      return unauthorized()
    u.upload_text = request.POST.get('upload_text')
    u.release_id = request.POST.get('release_id')
  else:
    u = Upload(upload_text = request.POST.get('upload_text'),
               release_id = request.POST.get('release_id'),
               user_id = request.user.id,
               pub_date = timezone.now()
              )
  u.save()

  upload_link_save(u, request.POST.get('links'))

  return HttpResponseRedirect(reverse('track:upload-view', args=(u.id,)))

@login_required
def upload_delete(request, upload_id):
  try:
    upload = get_object_or_404(Upload, pk=upload_id)
    if not upload.can_modify(request):
      return unauthorized()
  except:
    return HttpResponseRedirect(reverse('track:index', args=()))
  if 'sure' in request.GET:
    title_id = upload.release.title.id
    upload.delete()
    return HttpResponseRedirect(reverse('track:title-view', args=(title_id,)))
  return render(request, 'track/upload-delete.html', {'upload': upload})

@login_required
def upload_link_save(upload, links_text):
  def nl_protocol(protocol):
    return "\n" + protocol.group(0).lower()

  from django.db import IntegrityError
  from zlib import crc32

  link_crc32 = crc32(re.sub(r'([\n\r\t ]|\<.*)', '', links_text).encode())

  if upload.link_crc32 != link_crc32:
    upload.pub_date = timezone.now()
    upload.link_crc32 = link_crc32

  upload.link_set.all().delete()
  upload.upload_host_set.all().delete()

  host_list = []
  links_text = re.sub(r'((?<!\n)(ed2k|http|https|ftp)://|magnet:\?)', nl_protocol, links_text, flags=re.IGNORECASE)
  links = re.compile(r'(\w[^\<\n]+)\<?(.+)?').findall(links_text)
  for link, title in links:
    if title.strip() == "": title = link
    l = Link(link_url = link.strip(),
             link_text = title.strip()[:200],
             upload_id = upload.id)

    l.host_id = l.get_host()
    if l.host_id not in host_list:
      try:
        Host(hostname = l.host_id).save(force_insert = True)
      except IntegrityError:
        pass
    l.save()
    if l.host_id not in host_list:
      Upload_Host(upload_id = upload.id, host_id = l.host_id).save()
      host_list.append(l.host_id)

  host_list.sort()
  upload.host_list = ', '.join(host_list)

  upload.save()

@login_required
def upload_raw(request, upload_id):
  link_list = get_object_or_404(Upload, pk=upload_id).link_set.values_list('link_url', flat=True)
  return HttpResponse("\n".join(link_list), content_type='text/plain')

#
# Title
#
def title_list(request):
  return render(request, 'track/title-list.html', {'title_list': Title.objects.all().order_by('title_text')});

def title_view(request, title_id):
  title = get_object_or_404(Title, pk=title_id)
  return render(request, 'track/title-view.html', {'title': title})

@login_required
def title_edit_error(request, title_id, error):
  title = None
  if title_id != '0':
    title = get_object_or_404(Title, pk=title_id)
    if not title.can_modify(request):
      return unauthorized()
  return render(request, 'track/title-edit.html', {'title': title, 'error_message': error})

@login_required
def title_edit(request, title_id):
  if not request.POST:
    return title_edit_error(request, title_id, '')

  if request.POST.get('title_text').strip() == '':
    return title_edit_error(request, title_id, "El títol no pot estar buit")

  if request.POST.get('cover_url').strip() == '':
    return title_edit_error(request, title_id, "Heu d'asociar una imatge de portada")

  if title_id != '0':
    t = get_object_or_404(Title, pk=title_id)
    if not t.can_modify(request):
      return unauthorized()
    t.title_text = request.POST.get('title_text').strip()
    t.summary_text = request.POST.get('summary_text').strip()
    t.year_start = request.POST.get('year_start') or 0
    t.year_end = request.POST.get('year_end') or 0
    t.episodes = request.POST.get('episodes') or 0
    t.runtime_minutes = request.POST.get('runtime_minutes') or 0
    t.cover_url = request.POST.get('cover_url').strip()
  else:
    t = Title(title_text = request.POST.get('title_text').strip(),
              summary_text = request.POST.get('summary_text').strip(),
              year_start = request.POST.get('year_start') or 0,
              year_end = request.POST.get('year_end') or 0,
              episodes = request.POST.get('episodes') or 0,
              runtime_minutes = request.POST.get('runtime_minutes') or 0,
              cover_url = request.POST.get('cover_url').strip(),
             )

  if request.POST.get('status') is not None:
    t.status = request.POST.get('status')

  t.save()

  return HttpResponseRedirect(reverse('track:title-view', args=(t.id,)))

@login_required
def title_delete(request, title_id):
  try:
    if not request.user.is_staff:
      return unauthorized()
    title = get_object_or_404(Title, pk=title_id)
  except:
    return HttpResponseRedirect(reverse('track:index', args=()))
  if 'sure' in request.GET:
    title.delete()
    return HttpResponseRedirect(reverse('track:title-list', args=()))
  return render(request, 'track/title-delete.html', {'title': title})

#
# Release
#
@login_required
def release_edit_error(request, title_id, release_id, error):
  release = None

  if release_id != '0':
    release = get_object_or_404(Release, pk=release_id)
    if not release.can_modify(request):
      return unauthorized()

  title = get_object_or_404(Title, pk=title_id)
  return render(request, 'track/release-edit.html', {'title': title, 'release': release, 'error_message': error})

@login_required
def release_edit(request, title_id, release_id):
  if not request.POST:
    return release_edit_error(request, title_id, release_id, '')

  if request.POST.get('release_text').strip() == '':
    return release_edit_error(request, title_id, release_id, "Falta un comentari breu de la release")

  if request.POST.get('video_text').strip() == '':
    return release_edit_error(request, title_id, release_id, "Heu d'introduir la informació del vídeo")

  if request.POST.get('audio_text').strip() == '':
    return release_edit_error(request, title_id, release_id, "Heu d'introduir la informació del àudio")

  if release_id == '0':
    links_str = request.POST.get('links').strip()
    if links_str == "":
      return release_edit_error(request, title_id, release_id, "Falta la llista d'enllaços")

  if release_id != '0':
    r = get_object_or_404(Release, pk=release_id)
    if not r.can_modify(request):
      return unauthorized()
    r.release_text = request.POST.get('release_text').strip()
    r.video_text = request.POST.get('video_text').strip()
    r.audio_text = request.POST.get('audio_text').strip()
    r.subs_text = request.POST.get('subs_text').strip()
  else:
    r = Release(release_text = request.POST.get('release_text').strip(),
              video_text = request.POST.get('video_text').strip(),
              audio_text = request.POST.get('audio_text').strip(),
              subs_text = request.POST.get('subs_text').strip(),
              title_id = title_id,
              user_id = request.user.id,
              pub_date = timezone.now()
             )
  r.save()

  if request.POST.get('links', '') != '':
    if release_id == '0':
      u = Upload(release_id = r.id, user_id = r.user.id, pub_date = r.pub_date)
      u.save()
    else:
      u = r.upload_set.first()
    u.upload_text = request.POST.get('upload_text')
    upload_link_save(u, request.POST.get('links'))

  return HttpResponseRedirect(reverse('track:title-view', args=(title_id,)))

@login_required
def release_delete(request, title_id, release_id):
  try:
    release = get_object_or_404(Release, pk=release_id)
    if not release.can_modify(request):
      return unauthorized()
  except:
    return HttpResponseRedirect(reverse('track:index', args=()))
  if 'sure' in request.GET:
    release.delete()
    return HttpResponseRedirect(reverse('track:title-view', args=(title_id,)))
  return render(request, 'track/release-delete.html', {'release': release})

track/templates/track/auth-login.html
{% extends 'track/base.html' %}

{% block content %}
<p><h2>Accés</h2></p>

{% if error_message %}<p class='error'><strong>{{ error_message }}</strong></p>{% endif %}

<form method="post" action="{% url 'track:auth-login' %}">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ request.GET.next|default:next }}" />
  <input id="username" name="username" value="" placeholder="Usuari" autofocus />
  <br />
  <br />
  <input id="password" name="password" type="password" placeholder="Contrasenya" value="" />
  <br />
  <br />

  <input type="submit" value="Connectar" />
  <br />
  <br />
  <a href="{% url 'track:auth-register' %}?next={{ request.GET.next|default:next }}">Registrar nou usuari</a>
</form>
{% endblock %}

track/templates/track/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ca_ES">
<head>
  <link href="{% static 'track/style.css' %}" rel="stylesheet" type="text/css" />
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <title>{% block title %}Animelliure Track{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body {% block body %}{% endblock %}>
  <div id="banner">
    <img src='http://web.animelliure.net/images/site-logo-2.png' width=840 />
  </div>
  <div id="headbar">
    <table width=100%><tr>
      <td>
        <table><tr>
           <td class='header-button'><a href="{% url 'track:index' %}">TRACK</a></td>
           <td class='header-button'><a href="{% url 'track:title-list' %}">TÍTOLS</a></td>
           {% if user.is_authenticated %}
             <td class='header-button'><a href="{% url 'track:title-edit' 0 %}">NOU TÍTOL</a></td>
             <td class='header-button'><a href="{% url 'track:upload-edit' 0 %}">NOVA PUJADA</a></td>
           {% endif %}
        </tr></table>
      </td>
      <td width=10 class='medium pad1' style='text-align: right'>
        {% if user.is_authenticated %}
          {{ user.username }}<br />
          <a href="{% url 'track:auth-logout' %}?next={{ request.path|urlencode }}">desconnecta</a>
        {% else %}
          &nbsp;<br />&nbsp;
        {% endif %}
      </td>
     {% if not user.is_authenticated %}
       <td width=20>
         <table width=20><tr>
           <td width=20 class='header-button'><a href="{% url 'track:auth-login' %}?next={{ request.path|urlencode }}">CONNECTA</a></td>
         </tr></table>
       </td>
     {% endif %}
    </tr></table>
  </div>
  <div id="content">
    {% block content %}{% endblock %}
  </div>
</body>
</html>

track/templates/track/index.html
{% extends "track/base.html" %}
{% load static %}

{% block content %}
{% if upload_list %}
  <table width=100% cellspacing=10px>
    {% for upload in upload_list %}
      <tr><td class='infod infor'>
        <table width=100%>
          <tr>
            <td width=40px>
              <img src="{{ upload.release.title.cover_url }}" width=36px />
            </td>
            <td>
              <a href="{% url 'track:upload-view' upload.id %}">{{ upload.release.title.title_text }}</a>
              <br /><span>{{ upload.release.release_text }}</span>
              <br /><span class='small'>{{ upload.release.video_text }}</span>
              {% if upload.user.id != upload.release.user.id %}<br /><span class='small'>Release de {{ upload.release.user }}</span>{% endif %}
            </td>
            <td width=32% style='text-align: right'>
              <span>{{ upload.user }} - {{ upload.pub_date|date:'d.m.y H:i' }}</span><br /><br />
{#              {% if upload.upload_text != '' %}<span>{{ upload.upload_text }}</span><br />{% endif %} #}
              <span class='small'>{% for host in upload.get_upload_host_ordered %}
                  <a href="{% url 'track:upload-view' upload.id %}" class='nounderline'>
                  <img class='hosticon' src="{% static "track/images/"|add:host.host.image %}" title="{{ host.host }}" />
                </a>
              {% endfor %}</span>
            </td>
{#            <span style='float:right'> #}
{#              <a href="{% url 'track:upload-delete' upload.id %}">Borrar</a>&nbsp; #}
{#              <a href="{% url 'track:upload-edit' upload.id %}">Editar</a> #}
{#              </span> #}
          </tr>
        </table>
      </td></tr>
    {% endfor %}
  </table>
{% else %}
  <p>No n'hi ha de pujades</p>
{% endif %}
{% endblock %}

track/templates/track/release-delete.html
{% extends "track/base.html" %}

{% block content %}
<div class='dialog'>
  <span>Confirmeu que voleu esborrar la release "<strong>{{ release.title.title_text }} - {{ release.release_text }}</strong>"?</span>
  <br />
  <br />
  <br />
  <span class='error'>S'esborraran tots els enllaços !!!</span>
  <br />
  <br />
  <br />
  <br />
  <span class='dialog-button'><a href="{% url 'track:release-delete' release.title.id release.id %}?sure">Sí</a></span>
  <span class='dialog-button'><a href="{% url 'track:title-view' release.title.id %}">No</a></span>
</div>
{% endblock %}

track/templates/track/release-get-options.html
{% for release in release_list %}
  {# <option value="{{ release.id }}" {% if forloop.counter == 1 %}selected="selected"{% endif %}> #}
  <option value="{{ release.id }}">
    {% if release.release_text == '' %}{{ release.title.title_text }}{% else %}{{ release.release_text }}{% endif %} | {{ release.user }} | {{ release.pub_date|date:'d.m.y' }}
  </option>
{% endfor %}

track/templates/track/title-list.html
{% extends "track/base.html" %}

{% block content %}
{% if title_list %}
  <table width=100% cellspacing=10px>
    {% for title in title_list %}
      <tr><td class='infod infor'>
        <div>
          <a class='mar1' href="{% url 'track:title-view' title.id %}">{{ title.title_text }}</a>
          {% if user.is_staff or user.is_authenticated and title.status == 0 %}
          <span style='float:right'>
            {% if user.is_staff %}<a href="{% url 'track:title-delete' title.id %}">Borrar</a>&nbsp;{% endif %}
            <a href="{% url 'track:title-edit' title.id %}">Editar</a>
          </span>
          {% endif %}
          <br />
          {% if title.summary_text == '' %}
            <span class='small'>{{ title.summary_text|truncatechars:80 }}</span>
          {% endif %}
        </div>
      </td></tr>
    {% endfor %}
  </table>

{% else %}
  <p>No n'hi ha de animes</p>
{% endif %}
{% endblock %}

track/templates/track/title-view.html
{% extends "track/base.html" %}

{% block content %}
<table width=100%>
  <tr>
    <td class='infod' width=160><img width=160 src="{{ title.cover_url }}" /></td>
    <td class='infod'><br /><center><h2>{{ title.title_text }}</h2>
    <p class='pad2'>{{ title.summary_text }}</p></center></td>
  </tr>
</table>

<table width=100%>
  {% if title.year_start != 0 %}
    <tr>
      <td class='infot'>{% if title.year_end == 0 or title.year_start == title.year_end %}Any d'emissió{% else %}Primer any d'emissió{% endif %}</td>
      <td class='infod'>{{ title.year_start }}</td>
    </tr>
    {% if title.year_end != 0 and title.year_end != title.year_start %}
    <tr>
      <td class='infot'>Últim any d'emissió</td><td class='infod'>{{ title.year_end }}</td>
    </tr>
    {% endif %}
  {% endif %}
  {% if title.episodes != 0 %}
  <tr>
    <td class='infot'>Nombre d'episodis</td><td class='infod'>{{ title.episodes }}</td>
  </tr>
  {% endif %}
  {% if title.runtime_minutes != 0 %}
  <tr>
    <td class='infot'>Duració per capítol</td><td class='infod'>{{ title.runtime_minutes }} minuts</td>
  </tr>
  {% endif %}
  {% if title.status == 0 %}
  <tr>
    <td class='infot'>Estat de verificació</td><td class='infod'>Pendent de verificació</td>
  </tr>
  {% endif %}
  {% if user.is_authenticated %}
  <tr><td colspan='2' style='text-align: right'>
    {% if user.is_staff or title.status == 0 %}
      {% if user.is_staff %}<a href="{% url 'track:title-delete' title.id %}" >Borrar</a>&nbsp;{% endif %}
      <a href="{% url 'track:title-edit' title.id %}" >Editar</a>&nbsp;
    {% endif %}
    <a href="{% url 'track:release-edit' title.id 0 %}">Nova release</a>
  </td></tr>
  {% endif %}
</table>

<br /><br />

<table width=100%>
  <tr><td colspan='3' class='table-header'><center>
    <h2>Projectes</h2>
  </center></td></tr>
  {% for release in title.get_release_list %}
  <tr>
    <td class='infot'><h3>{{ release.release_text|default:release.title.title_text }}</h3></td>
    <td class='infod'>
      {% if user.is_authenticated %}
        <span style='float:right'>
          {% if user.id == release.user.id or user.is_staff %}
          <a href="{% url 'track:release-delete' title.id release.id %}">Borrar</a>&nbsp;
          <a href="{% url 'track:release-edit' title.id release.id %}">Editar</a>&nbsp;
          {% endif %}
          <a href="{% url 'track:release-upload' title.id release.id %}">Afegir distribució</a>
        </span>
      {% endif %}
      <span>{{ release.user }} - {{ release.pub_date|date:'d.m.Y' }}<span>
      {% if release.video_text != '' %}<br /><span class='small'>{{ release.video_text }}</span>{% endif %}
      {% if release.audio_text != '' %}<br /><span class='small'>{{ release.audio_text }}</span>{% endif %}
      {% if release.subs_text != '' %}<br /><span class='small'>Subtítols: {{ release.subs_text }}</span>{% endif %}
    </td>
  </td></tr>
  {% for upload in release.get_upload_list %}
  <tr>
    <td>&nbsp;</td>
    <td class='infod'><a href="{% url 'track:upload-view' upload.id %}">
      {{ upload.pub_date|date:'d.m.Y' }} - {{ upload.user }} - [{{ upload.host_list }}]
    </a>
    </td>
  </tr>
  {% endfor %}
  {% if not forloop.last %}<tr><td>&nbsp;</td><td>&nbsp;</td></tr>{% endif %}
  {% endfor %}
</table>
{% endblock %}

track/templates/track/upload-view.html
{% extends "track/base.html" %}

{% block content %}
<table width=100%>
  <tr>
    <td class='infod' width=160><img width=160 src="{{ upload.release.title.cover_url }}" /></td>
    <td class='infod'><br /><center><a href="{% url 'track:title-view' upload.release.title.id %}"><h2>{{ upload.release.title.title_text }}</h2></a>
    <p class='pad2'>{{ upload.release.title.summary_text }}</p></center></td>
  </tr>
</table>

<table width=100%>
  <tr>
    <td class='infot'>Muntador</td><td class='infod'>{{ upload.release.user }}</td>
  </tr>
  {% if upload.release.release_text %}
  <tr>
    <td class='infot'>Comentari del muntador</td><td class='infod'>{{ upload.release.release_text }}</td>
  </tr>
  {% endif %}
  {% if upload.release.video_text %}
  <tr>
    <td class='infot'>Informació del vídeo</td><td class='infod'>{{ upload.release.video_text }}</td>
  </tr>
  {% endif %}
  {% if upload.release.audio_text %}
  <tr>
    <td class='infot'>Informació del àudio</td><td class='infod'>{{ upload.release.audio_text }}</td>
  </tr>
  {% endif %}
  {% if upload.release.subs_text %}
  <tr>
    <td class='infot'>Informació de subtítols</td><td class='infod'>{{ upload.release.subs_text }}</td>
  </tr>
  {% endif %}
</table>

<br /><br />

<table width=100%>
  <tr><td class='table-header' colspan='3'><center><h2>Descàrrega</h2></center></td></tr>
  {% if user.is_authenticated %}
  <tr>
    <td colspan='3' class='infod' style='text-align: right'>
      <a href="{% url 'track:upload-raw' upload.id %}">Raw</a>&nbsp;
      {% if user.id == upload.user.id or user.is_staff %}
      <a href="{% url 'track:upload-delete' upload.id %}">Borrar</a>&nbsp;
      <a href="{% url 'track:upload-edit' upload.id %}">Editar</a>
      {% endif %}
    </td>
  </tr>
  {% endif %}
  <tr>
    <td colspan='3'>
      <table width=100%>
        <tr>
          <td class='infot'>Pujat per</td><td class='infod'>{{ upload.user }}</td>
        </tr>
        <tr>
          <td class='infot' rowspan='2'>Informació dels enllaços</td><td class='infod'>{{ upload.link_set.count }}, actualitzats el {{ upload.pub_date|date:'d.m.Y' }}</td>
        </tr>
        <tr>
          <td class='infod'>{{ upload.host_list }}</td>
        </tr>
        {% if upload.upload_text %}
        <tr>
          <td class='infot'>Comentari del uploader</td><td class='infod'>{{ upload.upload_text }}</td>
        </tr>
        {% endif %}
      </table>
      <br />
    </td>
  </tr>
  {% for link in upload.link_set.all %}
  <tr>
    <td class='infod' width=30px>{{ forloop.counter }}</td>
    <td class='infod' width=100px>{{ link.host }}</td>
    <td class='infod'><a href="{{ link.link_url }}">{{ link.link_text|truncatechars:80 }}</a></td>
  </tr>
  {% endfor %}
</table>
{% endblock %}